### ISSUE TITLE
Can't connect to server via vanilla `Lilypad QA`

### ISSUE THREAD

**Issue by Vladg24YT** [LilyBukkit/LilyBukkit-Core#37]
Client:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 8
	at java.lang.String.charAt(String.java:658)
	at kd.a(kd.java:140)
	at kd.a(kd.java:102)
	at lu.a(lu.java:407)
	at iq.b(iq.java:258)
	at net.minecraft.client.Minecraft.run(SourceFile:608)
	at java.lang.Thread.run(Thread.java:750)
```
Server:
```
11:19:34 [SEVERE] java.net.SocketException: Connection reset
11:19:34 [SEVERE]       at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
11:19:34 [SEVERE]       at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
11:19:34 [SEVERE]       at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
11:19:34 [SEVERE]       at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
11:19:34 [SEVERE]       at java.base/java.net.Socket$SocketInputStream.read(Socket.java:961)
11:19:34 [SEVERE]       at java.base/java.io.FilterInputStream.read(FilterInputStream.java:82)
11:19:34 [SEVERE]       at net.minecraft.src.Packet.readPacket(Packet.java:87)
11:19:34 [SEVERE]       at net.minecraft.src.NetworkManager.readPacket(NetworkManager.java:119)
11:19:34 [SEVERE]       at net.minecraft.src.NetworkManager.readNetworkPacket(NetworkManager.java:206)
11:19:34 [SEVERE]       at net.minecraft.src.NetworkReaderThread.run(NetworkReaderThread.java:17)
```

**Comment by Vladg24YT** [comment]
It's the FontRenderer bug

**Comment by Vladg24YT** [comment]
Tried another client, the issue is still present. Will try Smaed's jars next
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 8
	at java.lang.String.charAt(String.java:658)
	at kd.a(FontRenderer.java:135)
	at kd.a(FontRenderer.java:96)
	at lu.a(GuiIngame.java:333)
	at iq.b(EntityRenderer.java:253)
	at net.minecraft.client.Minecraft.run(Minecraft.java:490)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by Vladg24YT** [comment]
Ok, I'm dumb it was the Smaed's jar. Idk if it is fixable server-side though.

**Comment by Vladg24YT** [comment]
Closed as it's a client-side issue
